### ISSUE TITLE
pygments gem is not working on ruby 2.2.2 -> undefined method size on nil:NilClass Error.

### ISSUE THREAD

**Issue by collegeimprovements** [tmm1/pygments.rb#151]
`gem install pygments.rb`
                                                                
```ruby
ERROR:  Error installing pygments.rb:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Users/arpit/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/cache/pygments.rb-0.6.3.gem
```

And due to this reason `jekyll` is also failing.

**Comment by collegeimprovements** [comment]
Sorry for the trouble. My bad. Got it sorted out from above jekyll's issue page.
